### ISSUE TITLE
Test Case 3 (TC 3):  Stability

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/benchmarx#10]
A synchroniser is referred to as _stable_ if it maps idle deltas to idle deltas (i.e., if nothing was changed then nothing is done).  Note that _hippocraticness_ is more than this as the delta does not have to be idle.

**Comment by anthonyanjorin** [comment]
Suggested consistent precondition (constructed as a postcondition of #6 ):

**FamilyRegister** {
 - Skinner
 - Flanders
   - Rod (son)
 - Simpsons
    - Bart (father)
 - Simpsons
    - Homer (father)
    - Marge (mother)
    - Bart (son)
    - Bart (son)
    - Lisa (daughter)
    - Maggie (daughter)

}

**PersonRegister** {
 - Flanders, Rod (male)
 - Simpson, Bart (male)
 - Simpson, Homer (male)
 - Simpson, Marge (female)
 - Simpson, Bart (male)
 - Simpson, Bart (male)
 - Simpson, Lisa (female)
 - Simpson, Maggie (female)

}

The target delta to be propagated is idle, i.e., _nothing_ is changed in the person register.

The expected postcondition is the same as the precondition, i.e., tools should do nothing (corresponding to an idle delta on the family register).

**Comment by anthonyanjorin** [comment]
Features:  [**bwd** | **fixed** ]

No configuration is necessary so **fixed**

As the delta is idle, the test has no change type.  Handling the test requires neither an explicit correspondence model, nor explicit deltas.

**Comment by tbuchmann** [comment]
I'm confused. I thought this test consists of two fwd propagations in a row, where the second fwd propagation is issued after an idle delta. So the features should be [fwd | alignment-based | fixed] ?

**Comment by anthonyanjorin** [comment]
Good question.  

First point:  I'm confused myself how we should categorise test cases with respect to their **direction**.  Does establishing the precondition count or not?  If we think not, then this test should be **bwd**.  I chose to propagate a target idle delta instead of a source idle delta because it's more challenging to retain the family register (the person register could be easily recreated).  We have to decide here and be consequent.  Although I prefer ignoring how the precondition is established, it might be a bit surprising for tool developers to find forward propagations in a test labelled **bwd**.
In this test you would probably forward propagate the family register to establish the precondition as this does not require runtime configuration.

Second point:  alignment-based is an "abstract feature" in the feature model used only to structure the tree.  Normally an alignment-based test would have a change type (the feature is even mandatory), but with this strange idle delta, I don't know what change type to assign :)  
I don't really know what to do here:  (i) we could say the test is actually _not_ alignment-based as you could pass it just by keeping the old source model and checking if the delta is idle (and not performing any alignment).  (ii) We could adjust the feature model and add **idle** as a change type.

What do you think?

**Comment by tbuchmann** [comment]
If i remember right from our phone call, "stability" is a weaker form of hippocraticness. Thus, we need to test stability in either direction by calling two subsequent transformations in a row:
Test for fwd: Family Model -> fwd transformation -> expected Person Model -> "empty delta on Family Model" -> fwd transformation -> expectation: Person Model remains unchanged
The same test needs to be carried out in bwd direction.
From your description above, i think that changing the birthdate in the person model could be done in the hippocraticness test. If I understood you right, then hippocraticness should not affect the target model in case of irrelevant changes made in the source model.

According to the second point: I was looking for the feature "incremental" in the feature model, but i didn't find it :)
Since this type of test case can only be performed by tools, which support incremental behavior i chose "alingment-based" as it requires some kind of storing correspondences (from what i understood in the paper where the feature model is introduced).

**Comment by anthonyanjorin** [comment]
My suggestion is to test stability only in the backward direction, as the forward direction is in comparison boring (one could regenerate the person register from scratch).

I would agree that the hippocraticness test is certainly alignment-based, but this test is so basic, one could pass it just by keeping a copy of the old models and checking if the delta is idle.  This simple test does not require computing or keeping track of alignment information.

**Comment by tbuchmann** [comment]
Ok, i understand your point. However, we could think about introducing performance measurement somewhen in the future. Testing both fwd and bwd direction would make sense then (with larger models). The expectation would be that the second run of the transformation is performed in a shorter period of time.

**Comment by anthonyanjorin** [comment]
We should definitely provide performance measurement (the infrastructure is already there and was used for the benchmarx paper).  However I think we should separate this from these semantic tests.

My feeling is that we should not take how the precondition is set up into account, when determining the features of a test.  The argument is that you can choose to ignore this "history" by reacting only to the assertPrecondition call and setting your precondition there.  The history is only meant for delta-based tools that must build up some kind of consistent internal state and require everything in terms of deltas.  Agreed?  So even if configuration and fwd/bwd is used to establish the precondition of a test, this does _not_ affect the features of the test.  This means that this test (as I suggested it here in this issue) should indeed be [**bwd** | **fixed**].
