### ISSUE TITLE
Test Case 5 (TC 5):  Hippocraticness (strict check for EMF-based tools)

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/benchmarx#12]
Repeat TC 4 (#11), and additionally check if _exactly_ the same objects are present in the output model after synchronisation.

While this is not captured by any formal laws, this is of substantial practical relevance (e.g., in an EMF based context with dependent listeners, etc).  This test, however, only makes sense for EMF-based tools as arbitrary tools might not even run in a JVM context making it hard to formulate the test.

**Comment by tbuchmann** [comment]
I think we should skip this test for the TTC, because it might require some changes in the BenchmarX architecture, as we can not simply assert a postcondition.

**Comment by anthonyanjorin** [comment]
Ok
