### ISSUE TITLE
Test Case 6a (TC 6a):  Incr Fwd Insertions

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/benchmarx#13]
Suggested precondition:

**FamilyRegister** {
 - Skinner
 - Flanders
   - Rod (son)
 - Simpson
    - Bart (father)
 - Simpson
    - Homer (father)
    - Marge (mother)
    - Bart (son)
    - Bart (son)
    - Lisa (daughter)
    - Maggie (daughter)

}

**PersonRegister** {
 - Flanders, Rod (male)
 - Simpson, Bart (male)
 - Simpson, Homer (male)
 - Simpson, Marge (female)
 - Simpson, Bart (male)
 - Simpson, Bart (male)
 - Simpson, Lisa (female)
 - Simpson, Maggie (female)

}

Set birthdays of all persons in the person register (this must be propagated as a target delta so the tools' inner state is consistent).

Then propagate the source delta adding the following family members to the family Flanders:

- Ned (father)
- Maude (mother)
- Todd (son)

Expected postcondition:

**FamilyRegister** {
 - Skinner
 - Flanders
   - Rod (son)
   - Ned (father)
   - Maude (mother)
   - Todd (son)
 - Simpson
    - Bart (father)
 - Simpson
    - Homer (father)
    - Marge (mother)
    - Bart (son)
    - Bart (son)
    - Lisa (daughter)
    - Maggie (daughter)

}

**PersonRegister** {
 - Flanders, Rod (male)
 - Flanders, Ned (male)
 - Flanders, Maude (female)
 - Flanders, Todd (male)
 - Simpson, Bart (male)
 - Simpson, Homer (male)
 - Simpson, Marge (female)
 - Simpson, Bart (male)
 - Simpson, Bart (male)
 - Simpson, Lisa (female)
 - Simpson, Maggie (female)

}

**Comment by anthonyanjorin** [comment]
The only interesting thing about this test is that it checks if information loss in the persons register is avoided (birthdays must be preserved).  This rules out batch transformations.

**Comment by anthonyanjorin** [comment]
Features:  [**fwd** | **add** | **fixed** ]

I proposed **fwd** as setting birthdays is part of establishing the precondition.  We have to decide, however, how setting up the precondition influences this feature.  One could also view the direction as including the precondition (then it would be **round trip**).
Same discussion for change type, i.e., **add** vs. **add + attribute**.

It should be possible to pass this test without explicit deltas or correspondences (hence the test is neither **corr-based** nor **delta-based**.

**Comment by tbuchmann** [comment]
I tried to implement the test case as you described above. However, propagating birthday changes as target deltas (i supposed this is done by calling too.performAndPropagateTargetEdit) seems to raise a problem, even if the configuration parameter e (prefer existing families) is set to true.

**Comment by tbuchmann** [comment]
I added two new methods in the BXTool Interface:
- performSourceEdit
- performTargetEdit

They were required in order to get the incremental forward behavior for all TC6a-TC6e right.
If performAndPropagateTargetEdit is used instead, this creates a round-trip scenario in which e.g. medini failes on most preconditions, because the backward transformation destroys the family model.
