### ISSUE TITLE
Test Case 6b (TC 6b): Incremental Fwd Deletions

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/benchmarx#14]
Suggested precondition:

After creating the person register, set birthdays of all persons making sure that the Barts (sons) can be distinguished (this must be propagated as a target delta so the tools' inner state is consistent).

**FamilyRegister** {
 - Skinner
 - Flanders
   - Rod (son)
 - Simpson
    - Bart (father)
 - Simpson
    - Homer (father)
    - Marge (mother)
    - Bart (son) [younger son]
    - Bart (son) [older son]
    - Lisa (daughter)
    - Maggie (daughter)

}

**PersonRegister** {
 - Flanders, Rod (male)
 - Simpson, Bart (male)
 - Simpson, Homer (male)
 - Simpson, Marge (female)
 - Simpson, Bart (male) [younger son]
 - Simpson, Bart (male) [older son]
 - Simpson, Lisa (female)
 - Simpson, Maggie (female)

}

Then propagate the source delta deleting the younger Bart (son).

Expected postcondition:

**FamilyRegister** {
 - Skinner
 - Flanders
   - Rod (son)
 - Simpson
    - Bart (father)
 - Simpson
    - Homer (father)
    - Marge (mother)
    - Bart (son) [older son]
    - Lisa (daughter)
    - Maggie (daughter)

}

**PersonRegister** {
 - Flanders, Rod (male)
 - Simpson, Bart (male)
 - Simpson, Homer (male)
 - Simpson, Marge (female)
 - Simpson, Bart (male) [older son]
 - Simpson, Lisa (female)
 - Simpson, Maggie (female)

}

**Comment by anthonyanjorin** [comment]
Features:  [**fwd** | **del** | **corr-based** | **structural**]

**Comment by tbuchmann** [comment]
I added two new methods in the BXTool Interface:
- performSourceEdit
- performTargetEdit

They were required in order to get the incremental forward behavior for all TC6a-TC6e right.
If performAndPropagateTargetEdit is used instead, this creates a round-trip scenario in which e.g. medini failes on most preconditions, because the backward transformation destroys the family model.
