### ISSUE TITLE
Test Case 6e (TC 6e): Incremental Fwd Mixed

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/benchmarx#17]
Suggested precondition:

**FamilyRegister** {
 - Skinner
 - Flanders
   - Rod (son)
 - Simpson
    - Bart (father)
 - Simpson
    - Homer (father)
    - Marge (mother)
    - Bart (son)
    - Bart (son)
    - Lisa (daughter)
    - Maggie (daughter)

}

**PersonRegister** {
 - Flanders, Rod (male)
 - Simpson, Bart (male)
 - Simpson, Homer (male)
 - Simpson, Marge (female)
 - Simpson, Bart (male)
 - Simpson, Bart (male)
 - Simpson, Lisa (female)
 - Simpson, Maggie (female)

}

Set birthdays of all persons in the person register (this must be propagated as a target delta so the tools' inner state is consistent).

-------------

Then propagate the source delta deleting and re-creating Homer (father).

Expected postcondition:

**FamilyRegister** {
 - Skinner
   - Marge (mother)
 - Flanders
   - Rod (son)
   - Lisa (mother)
 - Simpson
    - Bart (father)
 - Simpson
    - Homer (father)
    - Bart (son)
    - Bart (son)
    - Maggie (daughter)

}

**PersonRegister** {
 - Flanders, Rod (male)
 - Simpson, Bart (male)
 - Simpson, Homer (male) [now with a default birthday]
 - Simpson, Marge (female)
 - Simpson, Bart (male)
 - Simpson, Bart (male)
 - Simpson, Lisa (female)
 - Simpson, Maggie (female)

}

**Comment by anthonyanjorin** [comment]
Features:  [**fwd** | **add+del** | **structural** | **fixed**]

As there is only one _Simpson, Homer_, I would argue that this test does not require explicit correspondence links, i.e., is not **corr-based**.

**Comment by anthonyanjorin** [comment]
Features:  [**fwd** | **structural** | **add+del** | **fixed**]

I don't think this test is **corr-based** as there is only one _Simpson, Homer_

**Comment by tbuchmann** [comment]
The description of the postcondition has a wrong family register. It should be:

FamilyRegister {

    Skinner
    Flanders
        Rod (son)
    Simpson
        Bart (father)
    Simpson
        Homer (father) <- the deleted and recreated one
        Marge (mother)
        Bart (son)
        Bart (son)
        Lisa (daughter)
        Maggie (daughter)

}

**Comment by tbuchmann** [comment]
I added two new methods in the BXTool Interface:
- performSourceEdit
- performTargetEdit

They were required in order to get the incremental forward behavior for all TC6a-TC6e right.
If performAndPropagateTargetEdit is used instead, this creates a round-trip scenario in which e.g. medini failes on most preconditions, because the backward transformation destroys the family model.
