### ISSUE TITLE
Test Case 7 (TC 7): Least Change

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/benchmarx#18]
Hi @tbuchmann 

I propose to close this issue as other tests already check "least change", e.g., the fwd incremental tests that are failing for eMoflon.

Do we really need/have a specifically specially interesting least change test case?

**Comment by tbuchmann** [comment]
Hi @anthonyanjorin 

i think we can close it as i don't think it is a mandatory case for the essential core of test cases.
