### ISSUE TITLE
Test Case 9a (TC 9a): Incremental Bwd Insertions

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/benchmarx#21]
Suggested precondition:

**FamilyRegister** {
 
 - Simpson
    - Homer (father)
    - Maggie (daughter)

}

**PersonRegister** {

 - Simpson, Homer (male)
 - Simpson, Maggie (female)

}

To finalise the precondition, set birthdays of all persons in the person register as an idle target delta.

----------------------------

Then for [e ^ p] propagate the target delta adding the following person:

Skinner, Seymour (male)

(although existing families are to be preferred, there is no suitable family in the family register so a new family Skinner with Seymour as father must be created)

Then for [e ^ p] propagate the target delta adding:

Skinner, Seymour (male)

(there is now a Skinner family so this must be used; as a father already exists the second configuration parameter has to be ignored adding Seymour as a son even though creating parents is preferred _if possible_)

Then for [!e ^ p] propagate the target delta adding:

Skinner, Seymour (male)

(although there is now a suitable Skinner family a new family must be created with Seymour as father)

Then for [!e ^ !p] propagate the target delta adding:

Skinner, Seymour (male)

(although there are suitable Skinner families a new family must be created with Seymour as son)

Then for [e ^ p] propagate the target delta adding:

Skinner, Seymour (male)

(there is one existing Skinner family where Seymour can be added as a father;  this must be used)

Finally, with [e ^ !p] propagate the target delta adding:

Simpson, Bart (male)
Simpson, Lisa (female)

(the existing Simpson family must be used, Bart and Lisa must be added as children)

Final expected postcondition:

**FamilyRegister** {
 - Skinner
    - Seymour (father)
    - Seymour (son) 
 - Skinner
    - Seymour (father)  
- Skinner
    - Seymour (son)
    - Seymour (father)
 - Simpson
    - Homer (father)
    - Bart (son)
    - Lisa (daughter)
    - Maggie (daughter)

}

**PersonRegister** {
 - Simpson, Homer (male)
 - Simpson, Bart (male)
 - Simpson, Lisa (female)
 - Simpson, Maggie (female)
 - Skinner, Seymour (male)
 - Skinner, Seymour (male) 
 - Skinner, Seymour (male) 
 - Skinner, Seymour (male)
 - Skinner, Seymour (male)

}

**Comment by anthonyanjorin** [comment]
Features : [**bwd** | **runtime** | **add** ]

I'm not sure if this is **delta-based** or/and **corr-based**.  I think perhaps not - so it is reasonable to expect that the test can be passed without external corrs and deltas.

What do you think @tbuchmann ?

**Comment by tbuchmann** [comment]
I'm also not sure if it is delta-based and/or corr-based. But i think we should split up the expected postconditions to match the different configurations. Or should we change the configuration on-the-fly during test case execution? Not sure if this is a good idea, as some tools might pass incremental backward transformations with fixed parameters, but may fail on others. Intermixing parameters can lead to results which are again hard to interpret.

**Comment by anthonyanjorin** [comment]
I would go with on-the-fly runtime configuration.  The steps in the test are basically very similar and could lead to an explosion of test cases if we extract all of them (for each group of tests) to separate test cases.

The configuration required here is in any case **runtime** in the sense that it cannot be fixed at design time.  I would be surprised if a tool fails for the combination but passes for separate tests where the configuration is still set at **runtime**.

I agree, however, that debugging is of course easier with separated tests.

As a compromise, how about checking (all/some) intermediate postconditions after each propagation?  So a single test case but multiple post condition assertions at all interesting locations.

**Comment by anthonyanjorin** [comment]
I would say it is neither **corr-based** nor **delta-based**, so the expected result can be produced with internally computed alignment (deltas and corrs).  This is not very surprising for insertions.

**Comment by tbuchmann** [comment]
Yes, that sounds good. As a different compromise, how about having 2 testcases: one with a fixed parameter configuration (let's pick the most interesting one for example) and one with dynamic reconfiguration as you suggested above. How does that sound?

**Comment by anthonyanjorin** [comment]
ok - I don't really understand what **fixed** means though...  It is still a runtime and not a design-time configuration right?

**Comment by tbuchmann** [comment]
I will split up the test cases, as discussed on the phone. Let's use e^p as a fixed parameter setting. Then the precondition for this test would be:

Suggested precondition:

PersonRegister {
    Simpson, Homer (male)
    Simpson, Maggie (female)
}

FamilyRegister {
    Simpson
        Homer (father)
        Maggie (mother)
}

To finalise the precondition, set birthdays of all persons in the person register as an idle target delta.

Then for [e ^ p] propagate the target delta adding the following person:

Skinner, Seymour (male)

(although existing families are to be preferred, there is no suitable family in the family register so a new family Skinner with Seymour as father must be created)

Then for [e ^ p] propagate the target delta adding:

Skinner, Seymour (male)

(there is now a Skinner family so this must be used; as a father already exists the second configuration parameter has to be ignored adding Seymour as a son even though creating parents is preferred if possible)

Expected Postcondition:

PersonRegister {
    Simpson, Homer (male)
    Simpson, Maggie (female)
    Skinner, Seymour (male)
    Skinner, Seymour (male)
}

FamilyRegister {
    Skinner
        Seymour (son)
        Seymour (father)
    Simpson
        Homer (father)
        Maggie (mother)
}

**Comment by tbuchmann** [comment]
This test case is already online, if you want to have a look. If it is ok, i will continue to supply all other incremental Bwd test cases in the same manner in this class.

**Comment by tbuchmann** [comment]
Test cases (fixed parameter configuration & dynamic parameter configuration) now completely implemented and working for eMoflon and BxTend
