### ISSUE TITLE
Test Case 9b (TC 9b): Incremental Bwd Deletions

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/benchmarx#22]
Suggested precondition:

**FamilyRegister** {
 
 - Simpson
    - Homer (father)
    - Maggie (daughter)

}

**PersonRegister** {

 - Simpson, Homer (male)
 - Simpson, Maggie (female)

}

To finalise the precondition, set birthdays of all persons in the person register as an idle target delta.

--------------------------------------------

Then propagate the target delta deleting all persons

Expected post condition:

**FamilyRegister** {
 
 - Simpson

}

**PersonRegister** {

}

**Comment by anthonyanjorin** [comment]
Features = [**bwd** | **del** ]

Note:  Another least change test

**Comment by tbuchmann** [comment]
As this is a backward test, the person register gets transformed into a family model. Depending on the parameter configuration, Homer and Maggie are transformed either as parents or as childs. Assuming parameter configuration e ^ p, the family register in the precondition looks like this:

FamilyRegister {
    Simpson
        Homer (father)
        Maggie (mother)
}

**Comment by anthonyanjorin** [comment]
I understand the problem...   Another solution could be to transform Homer with [e ^ p] and then Maggie with [e ^ !p].  This is not so important but the idea of the test was I think to cover both deletion of parents and children.

**Comment by tbuchmann** [comment]
Ok, that makes sense.

**Comment by tbuchmann** [comment]
implemented & online.
