### ISSUE TITLE
Test Case 9c (TC 9c): Incremental Bwd Renaming

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/benchmarx#23]
Suggested precondition:

**FamilyRegister** {
 - Skinner
 - Flanders
   - Rod (son)
 - Simpson
    - Bart (father) [1]
 - Simpson
    - Homer (father)
    - Marge (mother)
    - Bart (son) [2]
    - Bart (son) [3]
    - Lisa (daughter)
    - Maggie (daughter)

}

**PersonRegister** {
 - Flanders, Rod (male)
 - Simpson, Bart (male) [1]
 - Simpson, Homer (male)
 - Simpson, Marge (female)
 - Simpson, Bart (male) [2]
 - Simpson, Bart (male) [3]
 - Simpson, Lisa (female)
 - Simpson, Maggie (female)

}

---------------------------------

Then propagate the target delta renaming:

Simpson, Bart [2] to Simpson, Bartholomew

Then, with [e ^ p] propagate the target delta renaming:

Simpson, Bart [3] to Skinner, Seymour

Then, with [e ^ !p] propagate the target delta renaming:

Simpson, Bart [1] to Flanders, Todd

Then, with [!e ^ !p] rename:

Simpson, Lisa to Flanders, Lisa

And finally with [!e ^ p] rename:

Simpson, Marge to Flanders, Maude

Expected postcondition:

**FamilyRegister** {
 - Skinner
   -  Seymour (father) [3]
 - Flanders
   - Rod (son)
   - Todd (son) [1]
 - Flanders
    - Lisa (daughter)
 - Flanders
    - Marge (mother)
 - Simpson
 - Simpson
    - Homer (father)
    - Bartholomew (son) [2]
    - Maggie (daughter)

}

**PersonRegister** {
 - Flanders, Rod (male)
 - Simpson, Bart (male) [1]
 - Simpson, Homer (male)
 - Simpson, Marge (female)
 - Simpson, Bart (male) [2]
 - Simpson, Bart (male) [3]
 - Simpson, Lisa (female)
 - Simpson, Maggie (female)

}

**Comment by anthonyanjorin** [comment]
Features = [**bwd** | **attribute** | **structural** | **corr-based** |  **runtime**]

**Comment by anthonyanjorin** [comment]
@tbuchmann:  This test can also be decomposed into several tests.  For example, renaming Simpson, Bart [1] to Flanders, Todd tests for least change (the empty Simpson family should not be deleted in the source).

Also, the last renames of uniquely named persons are together not **corr-based** as the horizontal alignment could be easily computed.   They are still **structural**, however, as it is in general unclear if this was a rename or add+delete.

You can decide based on required effort how far you want to decompose.

**Comment by tbuchmann** [comment]
The postcondition does not match the description of the performed changes. It should be:

FamilyRegister {
    Skinner
        Seymour (father) [3]
    Flanders
        Rod (son)
        Todd (son) [1]
    Flanders
        Lisa (daughter)
    Flanders
        Maude (mother)
    Simpson
    Simpson
        Homer (father)
        Bartholomew (son) [2]
        Maggie (daughter)
}

PersonRegister {
    Flanders, Rod (male)
    Skinner, Seymour (male) [1]
    Simpson, Homer (male)
    Flanders, Maude (female)
    Simpson, Bartholomew (male) [2]
    Flanders, Todd (male) [3]
    Flanders, Lisa (female)
    Simpson, Maggie (female)
}

**Comment by anthonyanjorin** [comment]
You're right!
