### ISSUE TITLE
Test Case 6f (TC 6f): Incremental Fwd Mixed Gender

### ISSUE THREAD

**Issue by tbuchmann** [eMoflon/benchmarx#28]
Suggested precondition:

FamilyRegister {

    Skinner
    Flanders
        Rod (son)
    Simpson
        Bart (father)
    Simpson
        Homer (father)
        Marge (mother)
        Bart (son)
        Bart (son)
        Lisa (daughter)
        Maggie (daughter)

}

PersonRegister {

    Flanders, Rod (male)
    Simpson, Bart (male)
    Simpson, Homer (male)
    Simpson, Marge (female)
    Simpson, Bart (male)
    Simpson, Bart (male)
    Simpson, Lisa (female)
    Simpson, Maggie (female)

}

Set birthdays of all persons in the person register (this must be propagated as a target delta so the tools' inner state is consistent).

Then propagate the source delta of moving Maggie from the Simpsons family to the Flanders family. In the flanders family, Maggie does not take the role daughter, but the role son.

Expected postcondition:

Expected postcondition:

FamilyRegister {

    Skinner
        Marge (mother)
    Flanders
        Rod (son)
        Maggie (son)
    Simpson
        Bart (father)
    Simpson
        Homer (father)
        Bart (son)
        Bart (son)
        Lisa (daughter)

}

PersonRegister {

    Flanders, Rod (male)
    Simpson, Bart (male)
    Simpson, Homer (male) 
    Simpson, Marge (female)
    Simpson, Bart (male)
    Simpson, Bart (male)
    Simpson, Lisa (female)
    Flanders, Maggie (male) [newly created, but birthdate copied from previous female instance]

}

Do you think we should include this TC @anthonyanjorin ?

**Comment by anthonyanjorin** [comment]
Yes, it is certainly interesting.  And the expectation is a good example of "least change" I would say.
