### ISSUE TITLE
End of a synchronization dialogue

### ISSUE THREAD

**Issue by georghinkel** [eMoflon/benchmarx#37]
While the paper suggests that the assertion of a post-condition is the last item in every synchronization dialogue, there are actually tests such as IncrementalForward/testStability that have multiple post-condition assertions. 

NMF has to use a co-program approach and I therefore, I need to know when a synchronization dialogue is complete and I can exit the program, otherwise it is going to run endlessly. So how can I find out that a synchronization dialogue has ended?

**Comment by anthonyanjorin** [comment]
That's a good point.

@tbuchmann: Should we add an extra method `terminateSynchronisationDialogue()` in the tool interface, which we promise to invoke to signify the end of every dialogue?

**Comment by tbuchmann** [comment]
@anthonyanjorin : Yes i think this would be a good idea.

**Comment by anthonyanjorin** [comment]
Ok I'll do that and push the changes today or tomorrow.
@georghinkel You can then assume that every dialogue starts with an init and ends with a terminate.
