### ISSUE TITLE
Can't build the FamiliesToPersons project

### ISSUE THREAD

**Issue by tsdh** [eMoflon/benchmarx#44]
I followed the setup guide in the README.MD but after installing the Eclipse Modeling Tools bundle, eMoflon and Xtend, the 6 projects don't build without error automagically.  The FamiliesToPersons project complains that there are packages exported which it doesn't actually contain, and because that project won't build, the dependent project BechmarkxFamiliesToPersons doesn't build, too.

Here's a screenshot of the errors I get: 
![screenshot from 2017-05-12 20-05-13](https://cloud.githubusercontent.com/assets/103854/26010849/e10c40ae-374e-11e7-9e63-f620d7a402ba.png)

Well, I guess that's because there's nothing in the `gen/` directory but how do I get anything generated here?

**Comment by georghinkel** [comment]
Judging from the missing packages, I think that there is something wrong with the eMoflon installation. Did you try to reuse an existing Eclipse? For me, it only worked with a completely fresh Eclipse sticking exactly to the installation instructions.

**Comment by tsdh** [comment]
I installed a completely new eclipse using the new installer. However, I chose an existing workspace for it. Maybe that broke something? I'm gonna try...

**Comment by tsdh** [comment]
Indeed, after killing my workspace and starting anew, now I only have one error left: the package org.moflon.tie does not exist.  Well, and eclipse gets an unhandled event loop error every two minutes and wants to restart.  :-(

**Comment by tsdh** [comment]
This morning I tried with fresh installs of neon or oxygen. However, I always get non-resolvable dependency problems between xtend, emoflon, RCP, parsely (bundled with eclipse for modeling). This is really horrible.

**Comment by anthonyanjorin** [comment]
Sorry, I can't reproduce this :(

How about simply closing the problematic FamiliesToPersons project and removing eMoflon-specific parts in BenchmarxFamiliesToPersons from the build path?

That way you can work on your solution without getting all example solutions running (BiGUL can also be challenging depending on your Linux variant).

For a comparison when you're done we have setup a Share image with all solutions.

**Comment by anthonyanjorin** [comment]
I'll try to replace all project dependencies with jars this evening, so you only need to install the plugins.  I'll also try to replace the entire eMoflon dependency with a jar so installation is also unnecessary.

**Comment by georghinkel** [comment]
I am afraid the NMF solution will not run on SHARE at all. NMF runs on .net 4.5.1 which requires at least windows vista. Currently, even .net core does not support arch Linux.

**Comment by anthonyanjorin** [comment]
Dear @tsdh,

I have now uniformly added all tool dependencies as jars, making the main project executable with a fresh Eclipse Modelling Tools (no installation of anything else necessary).  All changes have been pushed to master.

I've also adjusted the README and just tried it out for a fresh Eclipse Modelling Tool installation (Neon3).  Could you please check if it works for you too?

Cheers,
Tony

PS: I had actually tried the old README for macOS Sierra, Windows 10, and Ubuntu 16, but I'm learning that that doesn't mean much.  Fascinating :)

**Comment by tsdh** [comment]
Thanks @anthonyanjorin,

now it almost works.  The only errors I get are in the FamiliesToPersons project where the java files in gen and src cannot import classes from the `org.moflon.tgg` package.

Well, and I still get those "unhandled event loop exceptions: no more handles"... :-(

**Comment by anthonyanjorin** [comment]
Not sure I understand.  You only need exactly one project in your workspace now.  All the other projects are for developing the solutions.

**Comment by tsdh** [comment]
Oh, I didn't re-read the README and assumed that now all six projects should compile without errors.  Then I'm closing this issue now.  Thx!

**Comment by tsdh** [comment]
Just in case someone else has these "no more handles" eclipse crashes, too: Eclipse or rather SWT don't work satisfactory with a Wayland compositor.  You can work around the issue by starting eclipse using `GDK_BACKEND=x11 ./eclipse`.
