### ISSUE TITLE
Save models after transformations

### ISSUE THREAD

**Issue by tsdh** [eMoflon/benchmarx#45]
I just started writing my solution and so far I can run it using JUnit.  However, 19 test cases fail and it is hard to tell what's the problem.  In the "Failure Trace" view I can see some textual representation of the model the test expected and what it actually got.  However, that's not too easy to interpret.

Would it be possible to change the framework to call the `saveModels(String name)` method after each transformation so that we can inspect the results afterwards?

In my case, I save the models there and also print some PDF visualizations.  It would also be nice to get a handle on the expected model so that I can print that, too, for comparing it with the actual result model.

**Comment by anthonyanjorin** [comment]
Hi Tassilo,

just to make sure I understand your suggestion before I start making wild changes...

Why don't you do what you want to do in your implementation of the `assertPrecondition` and `assertPostcondition` methods of your tool?  Even if you're extending `BXToolForEMF` you could still wrap some extras around a super call.

Would that work?  In those methods you have access to both actual and expected models.

Cheers,
Tony

**Comment by tsdh** [comment]
Ah, I haven't seen those and I guess that'll work. I'll report back is that's the case or not. However, probably I won't be able to work on the case until next weekend.

**Comment by tsdh** [comment]
Ok, tried that and it works ok.  So no changes needed.  Thx!
