### ISSUE TITLE
Timeout in BXToolTimer

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/benchmarx#51]
Currently, very slow tools can make it difficult to run scalability measurements (they have to be commented out for larger input).

A solution would be to inforce a specified timeout in the BXToolTimer.

**Comment by tsdh** [comment]
That would be a good feature but I also found the performance bottleneck in my solution and check if I can fix it on time.

**Comment by tsdh** [comment]
Nope, I can't.  Or rather, I fixed what I found but it didn't have a too big effect. :-(
