### ISSUE TITLE
Credentials for the SHARE image Ubuntu12LTS_BenchmarX

### ISSUE THREAD

**Issue by tsdh** [eMoflon/benchmarx#54]
I want to setup my SHARE demo as requested in the paper.  Unfortunately, there's not even git and maven installed, and I can't find a README with the sudo password so that I can install the dependencies I need for my solution.

Where do I have to look for it?

(Just to be clear, I don't use that exact image but requested a mutable clone of this image which I will update/modify for my solution.)

**Comment by anthonyanjorin** [comment]
Hi - our VM is also just a clone of the Ubuntu VM.  The username/password is in the description of the VM:  ubuntu/reverse

Hope that works,
Tony

**Comment by tsdh** [comment]
Thx, I'll try this evening.

**Comment by tsdh** [comment]
Works, thank you.
