### ISSUE TITLE
False test failure for testIncrementalInsertsDynamicConfig

### ISSUE THREAD

**Issue by georghinkel** [eMoflon/benchmarx#56]
The following two family registers are asserted as not equal according to the test framework (I have slightly improved the formatting):

**Expected**

```
FamilyRegister{
	families=[
		Family{
			familyName="Simpson",
			father=Just(FamilyMember{firstName="Homer"}),
			mother=Just(FamilyMember{firstName="Maggie"}),
			sons=[],
			daughters=[]
		},
		Family{
			familyName="Skinner",
			father=Just(FamilyMember{firstName="Seymour"}),
			mother=Nothing,
			sons=[],
			daughters=[]
		},
		Family{
			familyName="Skinner",
			father=Just(FamilyMember{firstName="Seymour"}),
			mother=Nothing,
			sons=[
				FamilyMember{firstName="Seymour"}
			],
			daughters=[]
		},
		Family{
			familyName="Skinner",
			father=Just(FamilyMember{firstName="Seymour"}),
			mother=Nothing,
			sons=[
				FamilyMember{firstName="Seymour"}
			],
			daughters=[]
		}
	]
}
```

**Actual**

```
FamilyRegister{
	families=[
		Family{
			familyName="Simpson",
			father=Just(FamilyMember{firstName="Homer"}),
			mother=Just(FamilyMember{firstName="Maggie"}),
			sons=[],
			daughters=[]
		},
		Family{
			familyName="Skinner",
			father=Nothing,
			mother=Nothing,
			sons=[
				FamilyMember{firstName="Seymour"}
			],
			daughters=[]
		},
		Family{
			familyName="Skinner",
			father=Just(FamilyMember{firstName="Seymour"}),
			mother=Nothing,
			sons=[],
			daughters=[]
		},
		Family{
			familyName="Skinner",
			father=Just(FamilyMember{firstName="Seymour"}),
			mother=Nothing,
			sons=[
				FamilyMember{firstName="Seymour"},
                                FamilyMember{firstName="Seymour"}
			],
			daughters=[]
		}
	]
}
```

The only difference between them is the order of the family skinner that appears multiple times. I thought that the order of the families in the family register would not be of importance. Is that correct? If so, then perhaps generating these string descriptions has some bug.

**Comment by georghinkel** [comment]
@anthonyanjorin @tbuchmann

**Comment by tbuchmann** [comment]
Can you plesae tell us, which postcondition assertion fails? As far as I can see from your code pasted above, the last family in your actual FamilyRegister has a father named Seymour and two sons with the same name. I just checked the expected models ("FamilyAfterBwdInsertion1-6.xmi") and none of them contains a Family Skinner with two sons. Maybe this is the reason why the test case fails?

**Comment by anthonyanjorin** [comment]
Another "diff":  Your actual model has a family with no father, while all families in the expected model have fathers.

**Comment by georghinkel** [comment]
The postcondition that fails is line 91 `util.assertPostcondition("FamilyAfterBwdInsertion5", "PersonAfterBwdInsertion5");`. But yes, indeed, there is a structural difference beyond the order.

However, given that the result is correct after the postcondition in line 84, it seems my solution just picked a different family "Skinner". But ah, now I see that the one that is picked now does have a father but there is a different family that has no father currently. That explains the difference.
