### ISSUE TITLE
FunnyQT SHARE image

### ISSUE THREAD

**Issue by tsdh** [eMoflon/benchmarx#60]
Hi all,

I just wanted to mention that my SHARE image as linked from the TTC homepage and my paper aren't ready yet. I've requested a mutable clone on Wednesday, 31st, but my request hasn't been approved yet. I'll make it as soon as I get the approval and report back.

That said, since the solution lives in its own GitHub repository and is also integrated in the benchmarx project, you should be easily able to run it anyhow.

Bye, Tassilo

**Comment by tsdh** [comment]
I got my clone approved but immediately hosed it by installing the suggested updates and installing the things I need for my solution (jdk8, maven, git).  The result was that rdesktop gets just a flickering screen which jumps between different resolutions and no way to get back in a usable state.

So if you are also still trying to get your SHARE demo running, **don't even think about installing updates (and I don't mean a dist upgrade; don't even install the important security updates!).**

New clone requested...

**Comment by tsdh** [comment]
Ok, the next clone was approved.  I installed git via the package manager and manually the jdk8, adjusted `/etc/environment` to set `JAVA_HOME` and extend `PATH` correctly.  Then I rebooted.  The machine started properly, but this time I'm not logged in automatically but I start into the login manager.  When I try to login as ubuntu with password "reverse", the screen turns blank for a second and I'm put back into the login manager again.

When I type a wrong password, it tells me so.  So it seems I'm using the right password (i.e., we can exclude a wrong keymap which makes me provide the wrong password), but still I can't login anymore.

Any hints?  Can I switch to a virtual linux console somehow?  (Strg-Alt-Fx are consumed by my own computer, and there doesn't seem to be a menu entry for switching to a console AFAICT).

**Comment by anthonyanjorin** [comment]
I had a bit of a hard time too.  How about removing the session completely and then requesting a new one?

**Comment by anthonyanjorin** [comment]
(I also tried updates and got the flickering screen :) )

**Comment by tsdh** [comment]
@anthonyanjorin Obviously I've tried terminating the session via the web interface and requesting a new one, both with the flickering image after an update and now with the cannot-login-anymore issue, too.  Unfortunately, this did not help for any of both issues.
