### ISSUE TITLE
Need more information to setup and execute the benchmarx

### ISSUE THREAD

**Issue by Stevengre** [eMoflon/benchmarx#76]
Before execution, I should follow this https://github.com/eMoflon/emoflon-ibex-tutorial/releases to resolve the dependence of `org.emoflon.ibex.common` and `org.emoflon.smartemf`.

**Comment by anthonyanjorin** [comment]
Hi @Stevengre,

no, the benchmark should have jars with all dependencies included.

Let me solve this problem and get back to you ASAP.

Cheers,
Tony

**Comment by Stevengre** [comment]
Hi @anthonyanjorin,

Thank you so much for your help with this issue. I'm looking forward to hearing back from you soon.

Cheers,
Jianhong

**Comment by anthonyanjorin** [comment]
Hi @Stevengre,

I just tried out the instructions from the README: https://github.com/eMoflon/benchmarx#how-to-setup-and-execute-the-benchmarx and things worked out as expected.

Only FunnyQT doesn't seem to work with a recent Java and/or Eclipse and had to be commented out (I've pushed all my changes to main).
The default branch for the repository has also changed from master to main - if you already tried to setup this workspace as documented, I suggest you delete your workspace/clone and try it now again.

Please follow the outlined steps as closely as possible and feel free to reopen this issue if things don't work out-of-the box.
I suggest you first of all skip BiGUL and NMF as they require an additional setup.  If everything else works then feel free to try them as well (the appropriate READMEs are referenced as documented).

Cheers,
Tony 

FYI: @tbuchmann
