### ISSUE TITLE
How to generate the same result in "Benchmarking bidirectional transformations: theory, implementation, application, and assessment", especially the figures?

### ISSUE THREAD

**Issue by Stevengre** [eMoflon/benchmarx#77]
How to generate Table 5, Fig.26, Fig.27, Fig.28, Fig.29 step by step?

**Comment by anthonyanjorin** [comment]
Hi @Stevengre,

creating the final plots requires some manual work with a plotting program (we used Google Sheets for this).

The values for the plots can be generated by running the benchmark.

The easiest would be for me to create a suitable tag and get back to you ASAP.  A few solutions were not fully integrated into the benchmark infrastructure and require a few extra steps (I’ll document this too if this is not already in the code).

Cheers,
Tony

**Comment by Stevengre** [comment]
Hi @anthonyanjorin,

I wanted to express my gratitude for your generous help. I am eagerly waiting for your update on the problem. In the meantime, I am going to attempt constructing a new BX implementation based on my framework. My hope is that the code will generate a csv or excel file with the conformance/performance results, allowing me to easily obtain the same table/figure for my framework optimization. 

Thank you again for your assistance.

Best regards,
Jianhong

**Comment by anthonyanjorin** [comment]
Hi @Stevengre, 

the current main branch (not master!) can be used to generate the measurement data used for our paper (see your other issue #76).
If you have any questions or encounter problems, please don't hesitate to reach out again.

Cheers,
Tony

FYI: @tbuchmann
