### ISSUE TITLE
Share some useful information for BiGUL configuration

### ISSUE THREAD

**Issue by Stevengre** [eMoflon/benchmarx#78]
1. GHC 8.0.2 + cabal 2.4.1.0
2. https://winlibs.com/ for `ar` program in Windows.

**Comment by anthonyanjorin** [comment]
Hi, I suggest you update https://github.com/eMoflon/benchmarx/blob/main/examples/familiestopersons/BenchmarxFamiliesToPersons/src/org/benchmarx/examples/familiestopersons/implementations/bigul/README-SETUP after a successful setup and issue a pull request with your improvements.

**Comment by Stevengre** [comment]
Hi, I have already submitted a pull request. I apologize for bothering you.

**Comment by Stevengre** [comment]
Hi, I have already submitted a pull request. I apologize for bothering you.
